-- For each department, how many appointments were scheduled
-- how much appointment revenue per department

SELECT d.dept_id, d.dept_name, COUNT(a.appointment_id) as count_appt, SUM(payment_amount) AS Revenue FROM appointment a
JOIN doctor doc ON  a.doct_id = doc.doct_id
JOIN department d ON doc.dept_id = d.dept_id

WHERE a.appointment_date IS NOT NULL AND a.appointment_status = 'Scheduled'
GROUP BY d.dept_id, d.dept_name
ORDER BY dept_id;

--Which doctors have handled at least 10 appointments
--total appointment revenue generated by each doctor

SELECT d.doct_id, d.fname, d.lname, COUNT(a.appointment_id) as appt_atleast_10, SUM(a.payment_amount) AS revenue
FROM appointment a
JOIN doctor d ON a.doct_id = d.doct_id
WHERE a.appointment_status = 'Completed'
GROUP BY d.doct_id, d.fname, d.lname
HAVING COUNT(a.appointment_id)>= 10 
ORDER BY revenue ASC
